version: '1'

tools:
    bandit:
        enabled: false
    eslint:
        enabled: false
    ethlint:
        enabled: false
    hadolint:
        enabled: false
    npmAudit:
        enabled: false
    phpmd:
        enabled: false
    pylint:
        enabled: false
    revive:
        enabled: false
    rubocop:
        enabled: false
    scsslint:
        enabled: false
    tslint:
        enabled: false
    phpstan:
        enabled: false
    tfsec:
        enabled: false